name: Dockerize Next.js application
on: push 
jobs:
   build-container:
     name: Build Docker container image 
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code 
         uses: action/checkout@v2
       - name: Publish to Github Packages
         uses: docker/build-push-action@v1
         with:
           username: ${{ USERNAME_GITHUB }}
           password: ${{ secrets.ACCESS_TOKEN_GITHUB }}
           registry: docker.pkg.github.com
           repository: ${{github.repositry}}/next
           tags: latest, ${{git.run_number}}
       - name: Publish to Docker Hub
         uses: docker/build-push-action@v1
         with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password:  ${{secrets.DOCKER_ACCESS_TOKEN}}
          repository: seesharpgo/next
          tags: latest, ${{ github.run_number }}
